package com.idlefamiliar;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * Maps an in-game animation ID to the skilling activity it represents, replacing
 * the old "any non-idle animation counts as skilling" heuristic that produced
 * false positives (e.g. the fishing loop replaying while walking to a bank).
 *
 * <h2>How the whitelist is built</h2>
 * The animation IDs below are an explicit, hard-coded whitelist. They were
 * originally discovered by sweeping the {@code HUMAN_<skill>*} families in
 * {@link net.runelite.api.gameval.AnimationID} by name prefix, then frozen as
 * literals here. (An earlier revision performed that sweep at runtime via Java
 * reflection; the RuneLite Plugin Hub forbids reflection, so the result is baked
 * in instead.) Each entry carries its source {@code AnimationID} constant name
 * as a comment for traceability. Adding a tool tier or new variant now means
 * adding its line here, rather than it being picked up automatically.
 *
 * <p>Only skills with a clean, unambiguous animation namespace are listed
 * (Woodcutting, Mining, Fishing, Smithing, Fletching, Herblore, Cooking,
 * Runecraft, Farming, Thieving). Combat, Ranged, Magic, Hunter, Firemaking,
 * Construction, Agility and others have no clean animation namespace, so their
 * skilling label comes from the authoritative XP-drop signal ({@code
 * onStatChanged}) in {@link IdleFamiliarPlugin} instead. Non-active poses
 * (idle/enter/no-items) were excluded during the sweep, so an animation absent
 * from every set returns {@link Optional#empty()} — emotes, eating, drinking
 * and teleport wind-ups are silently ignored.
 */
public class ActivityAnimationRegistry
{
	private static final int[] WOODCUTTING_ANIMATIONS = {
		7264, // HUMAN_WOODCUTTING_3A_AXE
		869, // HUMAN_WOODCUTTING_ADAMANT_AXE
		873, // HUMAN_WOODCUTTING_BLACK_AXE
		5383, // HUMAN_WOODCUTTING_BLESSED_AXE
		5384, // HUMAN_WOODCUTTING_BLESSED_AXE_MISS
		879, // HUMAN_WOODCUTTING_BRONZE_AXE
		8324, // HUMAN_WOODCUTTING_CRYSTAL_AXE
		13870, // HUMAN_WOODCUTTING_DEMONIC_PACT
		2846, // HUMAN_WOODCUTTING_DRAGON_AXE
		8325, // HUMAN_WOODCUTTING_GAUNTLET_AXE_HM
		8303, // HUMAN_WOODCUTTING_GILDED_AXE
		2117, // HUMAN_WOODCUTTING_INFERNAL_AXE
		877, // HUMAN_WOODCUTTING_IRON_AXE
		12025, // HUMAN_WOODCUTTING_LEAGUE_AXE
		871, // HUMAN_WOODCUTTING_MITHRIL_AXE
		867, // HUMAN_WOODCUTTING_RUNE_AXE
		875, // HUMAN_WOODCUTTING_STEEL_AXE
		12026, // HUMAN_WOODCUTTING_TRAILBLAZER_AXE
		24, // HUMAN_WOODCUTTING_TRAILBLAZER_AXE_NO_INFERNAL
		11939, // HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE
		11940, // HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE_NO_INFERNAL
	};
	private static final int[] MINING_ANIMATIONS = {
		7283, // HUMAN_MINING_3A_PICKAXE
		7284, // HUMAN_MINING_3A_PICKAXE_NOREACHFORWARD
		7282, // HUMAN_MINING_3A_PICKAXE_WALL
		628, // HUMAN_MINING_ADAMANT_PICKAXE
		6750, // HUMAN_MINING_ADAMANT_PICKAXE_NOREACHFORWARD
		6756, // HUMAN_MINING_ADAMANT_PICKAXE_WALL
		3873, // HUMAN_MINING_BLACK_PICKAXE
		6108, // HUMAN_MINING_BLACK_PICKAXE_NOREACHFORWARD
		3866, // HUMAN_MINING_BLACK_PICKAXE_WALL
		625, // HUMAN_MINING_BRONZE_PICKAXE
		6747, // HUMAN_MINING_BRONZE_PICKAXE_NOREACHFORWARD
		6753, // HUMAN_MINING_BRONZE_PICKAXE_WALL
		8347, // HUMAN_MINING_CRYSTAL_PICKAXE
		8350, // HUMAN_MINING_CRYSTAL_PICKAXE_NOREACHFORWARD
		8345, // HUMAN_MINING_CRYSTAL_PICKAXE_WALL
		13869, // HUMAN_MINING_DEMONIC_PACT
		7139, // HUMAN_MINING_DRAGON_PICKAXE
		7140, // HUMAN_MINING_DRAGON_PICKAXE_NOREACHFORWARD
		642, // HUMAN_MINING_DRAGON_PICKAXE_PRETTY
		643, // HUMAN_MINING_DRAGON_PICKAXE_PRETTY_NOREACHFORWARD
		335, // HUMAN_MINING_DRAGON_PICKAXE_PRETTY_WALL
		6758, // HUMAN_MINING_DRAGON_PICKAXE_WALL
		8348, // HUMAN_MINING_GAUNTLET_PICKAXE_HM
		8313, // HUMAN_MINING_GILDED_PICKAXE
		8314, // HUMAN_MINING_GILDED_PICKAXE_NOREACHFORWARD
		8312, // HUMAN_MINING_GILDED_PICKAXE_WALL
		9485, // HUMAN_MINING_HET_3A_PICKAXE
		9478, // HUMAN_MINING_HET_ADAMANT_PICKAXE
		9475, // HUMAN_MINING_HET_BLACK_PICKAXE
		9473, // HUMAN_MINING_HET_BRONZE_PICKAXE
		9486, // HUMAN_MINING_HET_CRYSTAL_PICKAXE
		9481, // HUMAN_MINING_HET_DRAGON_PICKAXE
		9482, // HUMAN_MINING_HET_DRAGON_PICKAXE_PRETTY
		9480, // HUMAN_MINING_HET_GILDED_PICKAXE
		9484, // HUMAN_MINING_HET_INFERNAL_PICKAXE
		9474, // HUMAN_MINING_HET_IRON_PICKAXE
		9487, // HUMAN_MINING_HET_LEAGUE_TRAILBLAZER_PICKAXE
		9477, // HUMAN_MINING_HET_MITHRIL_PICKAXE
		9479, // HUMAN_MINING_HET_RUNE_PICKAXE
		9476, // HUMAN_MINING_HET_STEEL_PICKAXE
		11834, // HUMAN_MINING_HET_TRAILBLAZER_PICKAXE
		9488, // HUMAN_MINING_HET_TRAILBLAZER_PICKAXE_NO_INFERNAL
		11835, // HUMAN_MINING_HET_TRAILBLAZER_RELOADED_PICKAXE
		11836, // HUMAN_MINING_HET_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL
		9483, // HUMAN_MINING_HET_ZALCANO_PICKAXE
		4482, // HUMAN_MINING_INFERNAL_PICKAXE
		4483, // HUMAN_MINING_INFERNAL_PICKAXE_NOREACHFORWARD
		4481, // HUMAN_MINING_INFERNAL_PICKAXE_WALL
		626, // HUMAN_MINING_IRON_PICKAXE
		6748, // HUMAN_MINING_IRON_PICKAXE_NOREACHFORWARD
		6754, // HUMAN_MINING_IRON_PICKAXE_WALL
		8787, // HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE
		8788, // HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_NOREACHFORWARD
		8786, // HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_WALL
		629, // HUMAN_MINING_MITHRIL_PICKAXE
		6751, // HUMAN_MINING_MITHRIL_PICKAXE_NOREACHFORWARD
		6757, // HUMAN_MINING_MITHRIL_PICKAXE_WALL
		624, // HUMAN_MINING_RUNE_PICKAXE
		6746, // HUMAN_MINING_RUNE_PICKAXE_NOREACHFORWARD
		6752, // HUMAN_MINING_RUNE_PICKAXE_WALL
		627, // HUMAN_MINING_STEEL_PICKAXE
		6749, // HUMAN_MINING_STEEL_PICKAXE_NOREACHFORWARD
		6755, // HUMAN_MINING_STEEL_PICKAXE_WALL
		11831, // HUMAN_MINING_TRAILBLAZER_PICKAXE
		11837, // HUMAN_MINING_TRAILBLAZER_PICKAXE_NOREACHFORWARD
		8887, // HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL
		8888, // HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_NOREACHFORWARD
		8886, // HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_WALL
		11825, // HUMAN_MINING_TRAILBLAZER_PICKAXE_WALL
		11832, // HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE
		11838, // HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NOREACHFORWARD
		11833, // HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL
		11839, // HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_NOREACHFORWARD
		11827, // HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_WALL
		11826, // HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_WALL
		8363, // HUMAN_MINING_ZALCANO_3A_PICKAXE
		8356, // HUMAN_MINING_ZALCANO_ADAMANT_PICKAXE
		8353, // HUMAN_MINING_ZALCANO_BLACK_PICKAXE
		8351, // HUMAN_MINING_ZALCANO_BRONZE_PICKAXE
		8364, // HUMAN_MINING_ZALCANO_CRYSTAL_PICKAXE
		8359, // HUMAN_MINING_ZALCANO_DRAGON_PICKAXE
		8360, // HUMAN_MINING_ZALCANO_DRAGON_PICKAXE_PRETTY
		8358, // HUMAN_MINING_ZALCANO_GILDED_PICKAXE
		8362, // HUMAN_MINING_ZALCANO_INFERNAL_PICKAXE
		8352, // HUMAN_MINING_ZALCANO_IRON_PICKAXE
		8789, // HUMAN_MINING_ZALCANO_LEAGUE_TRAILBLAZER_PICKAXE
		8355, // HUMAN_MINING_ZALCANO_MITHRIL_PICKAXE
		8346, // HUMAN_MINING_ZALCANO_PICKAXE
		8349, // HUMAN_MINING_ZALCANO_PICKAXE_NOREACHFORWARD
		8344, // HUMAN_MINING_ZALCANO_PICKAXE_WALL
		8357, // HUMAN_MINING_ZALCANO_RUNE_PICKAXE
		8354, // HUMAN_MINING_ZALCANO_STEEL_PICKAXE
		11840, // HUMAN_MINING_ZALCANO_TRAILBLAZER_PICKAXE
		8889, // HUMAN_MINING_ZALCANO_TRAILBLAZER_PICKAXE_NO_INFERNAL
		11841, // HUMAN_MINING_ZALCANO_TRAILBLAZER_RELOADED_PICKAXE
		11842, // HUMAN_MINING_ZALCANO_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL
		8361, // HUMAN_MINING_ZALCANO_ZALCANO_PICKAXE
	};
	private static final int[] FISHING_ANIMATIONS = {
		622, // HUMAN_FISHING_CASTING
		9349, // HUMAN_FISHING_CASTING_BRUT
		11745, // HUMAN_FISHING_CASTING_NPC
		8188, // HUMAN_FISHING_CASTING_PEARL
		8190, // HUMAN_FISHING_CASTING_PEARL_BRUT
		8189, // HUMAN_FISHING_CASTING_PEARL_FLY
		6932, // HUMAN_FISHING_CASTING_PEARL_OILY
		9350, // HUMAN_FISHING_ONSPOT_BRUT
		623, // HUMAN_FISH_ONSPOT
		8191, // HUMAN_FISH_ONSPOT_PEARL
		8193, // HUMAN_FISH_ONSPOT_PEARL_BRUT
		8192, // HUMAN_FISH_ONSPOT_PEARL_FLY
		7203, // HUMAN_FISH_ONSPOT_PEARL_OILY
		618, // HUMAN_HARPOON
		5108, // HUMAN_HARPOON_BARBED
		8336, // HUMAN_HARPOON_CRYSTAL
		7401, // HUMAN_HARPOON_DRAGON
		8337, // HUMAN_HARPOON_GAUNTLET_HM
		7402, // HUMAN_HARPOON_INFERNAL
		8784, // HUMAN_HARPOON_LEAGUE_TRAILBLAZER
		8783, // HUMAN_HARPOON_TRAILBLAZER
		88, // HUMAN_HARPOON_TRAILBLAZER_NO_INFERNAL
		11867, // HUMAN_HARPOON_TRAILBLAZER_RELOADED
		11868, // HUMAN_HARPOON_TRAILBLAZER_RELOADED_NO_INFERNAL
		620, // HUMAN_LARGENET
		11042, // HUMAN_LARGENET_LOOPING
		621, // HUMAN_SMALLNET
	};
	private static final int[] SMITHING_ANIMATIONS = {
		898, // HUMAN_SMITHING
		8911, // HUMAN_SMITHING_IMCANDO_HAMMER
		8894, // HUMAN_SMITHING_NOREPLACE
	};
	private static final int[] FLETCHING_ANIMATIONS = {
		1248, // HUMAN_FLETCHING
		8480, // HUMAN_FLETCHING_ADD_ARROW_TIPS
		8469, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_ADAMANT
		8466, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_BLURITE
		8463, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_BRONZE
		8471, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_DRAGON
		8464, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_IRON
		8468, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_MITHRIL
		8470, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_RUNE
		8465, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_SILVER
		8467, // HUMAN_FLETCHING_ADD_BOLT_FEATHERS_STEEL
		8477, // HUMAN_FLETCHING_ADD_BOLT_TIPS_ADAMANT
		8474, // HUMAN_FLETCHING_ADD_BOLT_TIPS_BLURITE
		8472, // HUMAN_FLETCHING_ADD_BOLT_TIPS_BRONZE
		8479, // HUMAN_FLETCHING_ADD_BOLT_TIPS_DRAGON
		8473, // HUMAN_FLETCHING_ADD_BOLT_TIPS_IRON
		8476, // HUMAN_FLETCHING_ADD_BOLT_TIPS_MITHRIL
		8478, // HUMAN_FLETCHING_ADD_BOLT_TIPS_RUNE
		8475, // HUMAN_FLETCHING_ADD_BOLT_TIPS_STEEL
		8486, // HUMAN_FLETCHING_ADD_DART_FEATHERS_ADAMANT
		9108, // HUMAN_FLETCHING_ADD_DART_FEATHERS_AMETHYST
		8482, // HUMAN_FLETCHING_ADD_DART_FEATHERS_BRONZE
		8488, // HUMAN_FLETCHING_ADD_DART_FEATHERS_DRAGON
		8483, // HUMAN_FLETCHING_ADD_DART_FEATHERS_IRON
		8485, // HUMAN_FLETCHING_ADD_DART_FEATHERS_MITHRIL
		8487, // HUMAN_FLETCHING_ADD_DART_FEATHERS_RUNE
		8484, // HUMAN_FLETCHING_ADD_DART_FEATHERS_STEEL
		8481, // HUMAN_FLETCHING_ADD_FEATHER
		5244, // HUMAN_FLETCHING_HUNTINGBOLTS
		11097, // HUMAN_FLETCHING_HUNTINGBOLTS_CHISEL
		11098, // HUMAN_FLETCHING_HUNTINGBOLTS_CHISEL_SINGLE
		13150, // HUMAN_FLETCHING_HUNTINGBOLTS_CHISEL_SINGLE_QUICK
		11096, // HUMAN_FLETCHING_HUNTINGBOLTS_SINGLE
		11524, // HUMAN_FLETCHING_NOXIOUS_HALBERD
		11100, // HUMAN_FLETCHING_SINGLE
		12329, // HUMAN_FLETCHING_SINGLE_ROCK_SHARD
	};
	private static final int[] HERBLORE_ANIMATIONS = {
		364, // HUMAN_HERBING_GRIND
		7319, // HUMAN_HERBING_GRIND_NPC
		11095, // HUMAN_HERBING_GRIND_RESTART
		363, // HUMAN_HERBING_VIAL
		11094, // HUMAN_HERBING_VIAL_RESTART
	};
	private static final int[] COOKING_ANIMATIONS = {
		896, // HUMAN_COOKING
		11735, // HUMAN_COOKING_LOOP
		10795, // HUMAN_COOKING_WALKMERGE_NORESTART
		897, // HUMAN_FIRECOOKING
	};
	private static final int[] RUNECRAFT_ANIMATIONS = {
		791, // HUMAN_RUNECRAFT
		9361, // HUMAN_RUNECRAFT_WALKMERGE
	};
	private static final int[] FARMING_ANIMATIONS = {
		1728, // HUMAN_FARMING
	};
	private static final int[] THIEVING_ANIMATIONS = {
		881, // HUMAN_PICKPOCKET
	};

	/**
	 * Player teleport animations: the Lumbridge home-teleport casting sequence
	 * ({@code HOME_TELEPORT_HUMAN_*}) plus the individually named spellbook /
	 * jewellery teleport casts.
	 */
	private static final int[] TELEPORT_ANIMATIONS = {
		11875, // HOME_TELEPORT_HUMAN_ECHOES_1
		11876, // HOME_TELEPORT_HUMAN_ECHOES_2
		11877, // HOME_TELEPORT_HUMAN_ECHOES_3
		11878, // HOME_TELEPORT_HUMAN_ECHOES_4
		11879, // HOME_TELEPORT_HUMAN_ECHOES_5
		8811, // HOME_TELEPORT_HUMAN_FIRE_1
		8812, // HOME_TELEPORT_HUMAN_FIRE_2
		8813, // HOME_TELEPORT_HUMAN_FIRE_3
		8815, // HOME_TELEPORT_HUMAN_FIRE_4
		8817, // HOME_TELEPORT_HUMAN_FIRE_5
		714, // HUMAN_CASTTELEPORT
		793, // HUMAN_CAST2_TELEPORT
	};

	/**
	 * Sailing salvaging plays a dedicated player animation with no clean
	 * {@code HUMAN_*} stem, so it is whitelisted explicitly. List the id(s) your
	 * client plays <em>while actively salvaging</em>; the skilling linger bridges
	 * the brief "reset" pose between rolls.
	 */
	private static final int[] SAILING_SALVAGE_ANIMATIONS = {
		13584, // salvaging hook pull (captured from the client debug log while salvaging)
	};

	private final Map<Integer, String> activityByAnimation;
	private final Set<Integer> teleportAnimations;

	private ActivityAnimationRegistry(Map<Integer, String> activityByAnimation, Set<Integer> teleportAnimations)
	{
		this.activityByAnimation = activityByAnimation;
		this.teleportAnimations = teleportAnimations;
	}

	/**
	 * @return the activity label for {@code animationId}, or {@link Optional#empty()}
	 *         if it is not a recognised skilling animation
	 */
	public Optional<String> getActivityForAnimation(int animationId)
	{
		return Optional.ofNullable(activityByAnimation.get(animationId));
	}

	/** @return {@code true} if {@code animationId} is a known teleport animation */
	public boolean isTeleportAnimation(int animationId)
	{
		return teleportAnimations.contains(animationId);
	}

	/** Build the immutable registry from the baked whitelists above. */
	public static ActivityAnimationRegistry build()
	{
		Map<Integer, String> byAnimation = new HashMap<>();
		register(byAnimation, WOODCUTTING_ANIMATIONS, "Woodcutting");
		register(byAnimation, MINING_ANIMATIONS, "Mining");
		register(byAnimation, FISHING_ANIMATIONS, "Fishing");
		register(byAnimation, SMITHING_ANIMATIONS, "Smithing");
		register(byAnimation, FLETCHING_ANIMATIONS, "Fletching");
		register(byAnimation, HERBLORE_ANIMATIONS, "Herblore");
		register(byAnimation, COOKING_ANIMATIONS, "Cooking");
		register(byAnimation, RUNECRAFT_ANIMATIONS, "Runecraft");
		register(byAnimation, FARMING_ANIMATIONS, "Farming");
		register(byAnimation, THIEVING_ANIMATIONS, "Thieving");

		// Sailing salvaging wins over any earlier mapping for the same id.
		for (int salvageAnimation : SAILING_SALVAGE_ANIMATIONS)
		{
			byAnimation.put(salvageAnimation, "Sailing");
		}

		Set<Integer> teleports = new HashSet<>();
		for (int teleportAnimation : TELEPORT_ANIMATIONS)
		{
			teleports.add(teleportAnimation);
		}

		return new ActivityAnimationRegistry(
			Collections.unmodifiableMap(byAnimation),
			Collections.unmodifiableSet(teleports));
	}

	/** putIfAbsent each id under {@code label}, preserving any earlier (higher-priority) mapping. */
	private static void register(Map<Integer, String> byAnimation, int[] animations, String label)
	{
		for (int animation : animations)
		{
			byAnimation.putIfAbsent(animation, label);
		}
	}
}
